insert into estado (id, nome) values(1,'Alagoas');
insert into estado (id, nome) values(2,'Acre');
insert into estado (id, nome) values(3,'Amapá');
insert into estado (id, nome) values(4,'Amazonas');
insert into estado (id, nome) values(5,'Bahia');
insert into estado (id, nome) values(6,'Ceará');
insert into estado (id, nome) values(7,'Distrito Federal');
insert into estado (id, nome) values(8,'Espírito Santo');
insert into estado (id, nome) values(9,'Goiás');
insert into estado (id, nome) values(10,'Maranhão');
insert into estado (id, nome) values(11,'Mato Grosso');
insert into estado (id, nome) values(12,'Mato Grosso do Sul');
insert into estado (id, nome) values(13,'Minas Gerais');
insert into estado (id, nome) values(14,'Pará');
insert into estado (id, nome) values(15,'Paraíba');
insert into estado (id, nome) values(16,'Paraná');
insert into estado (id, nome) values(17,'Pernambuco');
insert into estado (id, nome) values(18,'Piauí');
insert into estado (id, nome) values(19,'Rio de Janeiro');
insert into estado (id, nome) values(20,'Rio Grande do Norte');
insert into estado (id, nome) values(21,'Rio Grande do Sul');
insert into estado (id, nome) values(22,'Rondônia');
insert into estado (id, nome) values(23,'Roraima');
insert into estado (id, nome) values(24,'Santa Catarina');
insert into estado (id, nome) values(25,'São Paulo');
insert into estado (id, nome) values(26,'Sergipe');
insert into estado (id, nome) values(27,'Tocantins');